# Stage3

## 함께실습$1

In [1]:
import numpy as np

np.array([1, 3, 5])

np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

## 함께실습$2

In [2]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## 함께실습$3

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a.shape

(3, 4)

## 함께실습$4

In [4]:
a = np.array(['a', 'b', 3, 4])
print(a[1:3])

['b' '3']


In [5]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 0행부터 1행까지, 1행부터 2열까지
print(b[0:2, 1:3])

# 모든 행, 1행부터 2행까지
print(b[:, 1:3])

# 1행부터 끝행, 모든 열
print(b[1:, :])

# 전부
print(b[:, :])

[[2 3]
 [6 7]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 함께실습$5

In [6]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[2,3] = 1
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  1]])

## 미션$1

In [7]:
mission = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

# 이 부분에 코드를 추가해주세요.
# 미션 코드 채울 부분
# code

mission[2,2] = 777
print(mission[:3, 2:])

# 아래와 Out과 같은 결과가 나오게 해주세요.

[[  3   4]
 [  7   8]
 [777  12]]


## 함께실습$6

In [8]:
n1 = np.array([3, 6, 9])

print(n1) # [3 6 9]
print(n1 + 5)
print(n1 - 5)
print(n1 * 5)
print(n1 / 5)
print(n1 % 5)

[3 6 9]
[ 8 11 14]
[-2  1  4]
[15 30 45]
[0.6 1.2 1.8]
[3 1 4]


## 함께실습$7

In [9]:
n2 = np.array([1, 2, 3])

print(n1 + n2)
print(n1 - n2)
print(n1 * n2)
print(n1 / n2)
print(n2 % n1)
print(n1.dot(n2)) # 내적

[ 4  8 12]
[2 4 6]
[ 3 12 27]
[3. 3. 3.]
[1 2 3]
42


## 함께실습$8

In [10]:
n3 = np.array([[1, 2, 3, 4], [5, 6, 9, 10]])
print(np.max(n3))
print(np.min(n3))
print(np.mean(n3)) # or np.average
print(np.median(n3))
print(np.var(n3))
print(np.std(n3))

10
1
5.0
4.5
9.0
3.0


## 함께실습$9

In [11]:
print(n3)

print('------------')
# print(n3 중에 4 이상인 자리만 True로 바꿔줘)
print(n3 >= 4)

print('------------')
# print(n3[True 표시된 부분만 선택해줘])
print(n3[n3 >= 4])

[[ 1  2  3  4]
 [ 5  6  9 10]]
------------
[[False False False  True]
 [ True  True  True  True]]
------------
[ 4  5  6  9 10]


## 함께실습$10

In [12]:
import pandas as pd

s1 = pd.Series({ '김': 100, '나': 141, '박': 129, '이': 124 })
s1.name = '수학'
print(s1)
print('------------')

s2 = pd.Series({ '김': 30, '나': 5, '박': 1239, '이': 141 })
# name을 안지어주면 어떻게 될까요?
print(s2)
print('------------')

s3 = pd.Series([8, 3, 12, 2]) # index를 지정 안하면 어떻게 될까요?
s3.name = '국어'
print(s3)
print('------------')

s4 = pd.Series([30, 5, 1239, 141])
# name, index 모두 지정 안하면 어떻게 될까요?
print(s4)

김    100
나    141
박    129
이    124
Name: 수학, dtype: int64
------------
김      30
나       5
박    1239
이     141
dtype: int64
------------
0     8
1     3
2    12
3     2
Name: 국어, dtype: int64
------------
0      30
1       5
2    1239
3     141
dtype: int64


## 함께실습$11

In [13]:
df = pd.DataFrame({ '출생지': ['한국','미국'], '나이': [20,30] })
df

출생지  나이
0  한국  20
1  미국  30

## 함께실습$12

In [14]:
# 열 추가
df['성별'] = ['여', '남']
df

출생지  나이 성별
0  한국  20  여
1  미국  30  남

In [15]:
# 행 추가
df.loc[2] = ['일본', 25, '여']
df

출생지  나이 성별
0  한국  20  여
1  미국  30  남
2  일본  25  여

## 함께실습$13

In [16]:
df2 = pd.DataFrame(s1)

df2['영어'] = s2
df2['미술'] = [1, 2, 3, 4]

df2

수학    영어  미술
김  100    30   1
나  141     5   2
박  129  1239   3
이  124   141   4

## 함께실습$14

In [17]:
df2[['수학', '미술']]

수학  미술
김  100   1
나  141   2
박  129   3
이  124   4

In [18]:
df2.loc[['김', '박']]

수학    영어  미술
김  100    30   1
박  129  1239   3

In [19]:
df2.loc[['김'],['미술']]

미술
김   1

## 함께실습$15

In [20]:
df2

수학    영어  미술
김  100    30   1
나  141     5   2
박  129  1239   3
이  124   141   4

In [21]:
print(df2.sum()) # df2.sum(axis=0)과 같습니다.
print(df2.mean(axis=1))

print(df2['수학'].mean())


수학     494
영어    1415
미술      10
dtype: int64
김     43.666667
나     49.333333
박    457.000000
이     89.666667
dtype: float64
123.5


## 미션$2

어떤 명령일지 해석해보세요.

> ,(콤마)를 기준으로 왼쪽은 행, 오른쪽은 열을 필터링합니다.  
> **"영어 점수가 100점 이상인 학생만 뽑아 그들의 수학점수 평균을 보여달라"**

In [22]:
print(df2.loc[df2['영어'] >= 100, '수학'].mean())

126.5


In [29]:
print(df2.loc[df2['영어'] >= 100].mean())

수학    126.5
영어    690.0
미술      3.5
dtype: float64


In [32]:
print(df2.loc[df2['영어'] >= 100].count())

수학    2
영어    2
미술    2
dtype: int64
